<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Workflow\ActionsButtonService' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'ActionsButtonService.php';

return $this->privates['Pimcore\\Workflow\\ActionsButtonService'] = new \Pimcore\Workflow\ActionsButtonService(($this->services['Pimcore\\Workflow\\Manager'] ?? $this->load('getManagerService.php')));
