<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Migrations\Configuration\ConfigurationFactory' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Migrations'.\DIRECTORY_SEPARATOR.'Configuration'.\DIRECTORY_SEPARATOR.'ConfigurationFactory.php';

return $this->services['Pimcore\\Migrations\\Configuration\\ConfigurationFactory'] = new \Pimcore\Migrations\Configuration\ConfigurationFactory($this, [0 => ['identifier' => 'app', 'name' => 'Migrations', 'namespace' => 'App\\Migrations', 'directory' => (\dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app/Migrations'), 'connection' => NULL], 1 => ['identifier' => 'pimcore_core', 'name' => 'Pimcore Core Migrations', 'namespace' => 'Pimcore\\Bundle\\CoreBundle\\Migrations', 'directory' => (\dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app/../vendor/pimcore/pimcore/bundles/CoreBundle/Migrations'), 'connection' => NULL]]);
