<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Routing\Redirect\Csv' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Routing'.\DIRECTORY_SEPARATOR.'Redirect'.\DIRECTORY_SEPARATOR.'Csv.php';

return $this->privates['Pimcore\\Routing\\Redirect\\Csv'] = new \Pimcore\Routing\Redirect\Csv();
