<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Http\ClientFactory' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'ClientFactory.php';

return $this->services['Pimcore\\Http\\ClientFactory'] = new \Pimcore\Http\ClientFactory(($this->services['Pimcore\\Config'] ?? ($this->services['Pimcore\\Config'] = new \Pimcore\Config())));
