<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Model\DataObject\ClassDefinition\ClassLayoutDefinitionManager' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'DataObject'.\DIRECTORY_SEPARATOR.'ClassDefinition'.\DIRECTORY_SEPARATOR.'ClassLayoutDefinitionManager.php';

return $this->services['Pimcore\\Model\\DataObject\\ClassDefinition\\ClassLayoutDefinitionManager'] = new \Pimcore\Model\DataObject\ClassDefinition\ClassLayoutDefinitionManager();
