<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Cache\Symfony\CacheClearer' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Cache'.\DIRECTORY_SEPARATOR.'Symfony'.\DIRECTORY_SEPARATOR.'CacheClearer.php';

return $this->services['Pimcore\\Cache\\Symfony\\CacheClearer'] = new \Pimcore\Cache\Symfony\CacheClearer();
