<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Bundle\CoreBundle\EventListener\Frontend\DocumentRendererListener' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'bundles'.\DIRECTORY_SEPARATOR.'CoreBundle'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'Frontend'.\DIRECTORY_SEPARATOR.'DocumentRendererListener.php';

return $this->privates['Pimcore\\Bundle\\CoreBundle\\EventListener\\Frontend\\DocumentRendererListener'] = new \Pimcore\Bundle\CoreBundle\EventListener\Frontend\DocumentRendererListener(($this->services['pimcore.templating.view_helper.placeholder.container_service'] ?? $this->load('getPimcore_Templating_ViewHelper_Placeholder_ContainerServiceService.php')));
