<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Model\Document\Editable\Loader\EditableLoader' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'LoaderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'ClassNameLoaderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'ImplementationLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'Document'.\DIRECTORY_SEPARATOR.'Editable'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'EditableLoaderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'Document'.\DIRECTORY_SEPARATOR.'Editable'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'EditableLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'AbstractClassNameLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'ClassMapLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'PrefixLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'Document'.\DIRECTORY_SEPARATOR.'Editable'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'PrefixLoader.php';

return $this->services['Pimcore\\Model\\Document\\Editable\\Loader\\EditableLoader'] = new \Pimcore\Model\Document\Editable\Loader\EditableLoader([0 => new \Pimcore\Loader\ImplementationLoader\ClassMapLoader(['href' => '\\Pimcore\\Model\\Document\\Editable\\Relation', 'multihref' => '\\Pimcore\\Model\\Document\\Editable\\Relations']), 1 => new \Pimcore\Model\Document\Editable\Loader\PrefixLoader([0 => '\\Pimcore\\Model\\Document\\Editable\\', 1 => '\\Document_Tag_'])]);
