<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Translation\ExportService\ExportServiceInterface' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportService'.\DIRECTORY_SEPARATOR.'ExportServiceInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportService'.\DIRECTORY_SEPARATOR.'ExportService.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService'.\DIRECTORY_SEPARATOR.'ExportDataExtractorServiceInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService'.\DIRECTORY_SEPARATOR.'DataExtractor'.\DIRECTORY_SEPARATOR.'DataExtractorInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService'.\DIRECTORY_SEPARATOR.'DataExtractor'.\DIRECTORY_SEPARATOR.'AbstractElementDataExtractor.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService'.\DIRECTORY_SEPARATOR.'DataExtractor'.\DIRECTORY_SEPARATOR.'DataObjectDataExtractor.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ExportDataExtractorService'.\DIRECTORY_SEPARATOR.'DataExtractor'.\DIRECTORY_SEPARATOR.'DocumentDataExtractor.php';

$a = new \Pimcore\Translation\ExportDataExtractorService\ExportDataExtractorService();
$a->registerDataExtractor('object', new \Pimcore\Translation\ExportDataExtractorService\DataExtractor\DataObjectDataExtractor());
$a->registerDataExtractor('document', new \Pimcore\Translation\ExportDataExtractorService\DataExtractor\DocumentDataExtractor(($this->services['Pimcore\\Document\\Editable\\EditableUsageResolver'] ?? $this->load('getEditableUsageResolverService.php'))));

return $this->privates['Pimcore\\Translation\\ExportService\\ExportServiceInterface'] = new \Pimcore\Translation\ExportService\ExportService($a, ($this->privates['Pimcore\\Translation\\ExportService\\Exporter\\ExporterInterface'] ?? $this->load('getExporterInterfaceService.php')));
