<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\GeoIp' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Targeting'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'DataProviderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Targeting'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'GeoIp.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'geoip2'.\DIRECTORY_SEPARATOR.'geoip2'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ProviderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'geoip2'.\DIRECTORY_SEPARATOR.'geoip2'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Database'.\DIRECTORY_SEPARATOR.'Reader.php';

$this->privates['Pimcore\\Targeting\\DataProvider\\GeoIp'] = $instance = new \Pimcore\Targeting\DataProvider\GeoIp(new \GeoIp2\Database\Reader(''), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->setCache(($this->services['pimcore.cache.core.handler'] ?? $this->getPimcore_Cache_Core_HandlerService()));

return $instance;
