<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Translation\ImportDataExtractor\ImportDataExtractorInterface' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImportDataExtractor'.\DIRECTORY_SEPARATOR.'ImportDataExtractorInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImportDataExtractor'.\DIRECTORY_SEPARATOR.'Xliff12DataExtractor.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImportDataExtractor'.\DIRECTORY_SEPARATOR.'TranslationItemResolver'.\DIRECTORY_SEPARATOR.'TranslationItemResolverInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImportDataExtractor'.\DIRECTORY_SEPARATOR.'TranslationItemResolver'.\DIRECTORY_SEPARATOR.'TranslationItemResolver.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'Escaper'.\DIRECTORY_SEPARATOR.'Xliff12Escaper.php';

return $this->privates['Pimcore\\Translation\\ImportDataExtractor\\ImportDataExtractorInterface'] = new \Pimcore\Translation\ImportDataExtractor\Xliff12DataExtractor(($this->privates['Pimcore\\Translation\\Escaper\\Xliff12Escaper'] ?? ($this->privates['Pimcore\\Translation\\Escaper\\Xliff12Escaper'] = new \Pimcore\Translation\Escaper\Xliff12Escaper())), new \Pimcore\Translation\ImportDataExtractor\TranslationItemResolver\TranslationItemResolver());
