<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Translation\ImporterService\ImporterServiceInterface' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImporterService'.\DIRECTORY_SEPARATOR.'ImporterServiceInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImporterService'.\DIRECTORY_SEPARATOR.'ImporterService.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImporterService'.\DIRECTORY_SEPARATOR.'Importer'.\DIRECTORY_SEPARATOR.'ImporterInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImporterService'.\DIRECTORY_SEPARATOR.'Importer'.\DIRECTORY_SEPARATOR.'AbstractElementImporter.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImporterService'.\DIRECTORY_SEPARATOR.'Importer'.\DIRECTORY_SEPARATOR.'DataObjectImporter.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'ImporterService'.\DIRECTORY_SEPARATOR.'Importer'.\DIRECTORY_SEPARATOR.'DocumentImporter.php';

$this->privates['Pimcore\\Translation\\ImporterService\\ImporterServiceInterface'] = $instance = new \Pimcore\Translation\ImporterService\ImporterService();

$instance->registerImporter('object', new \Pimcore\Translation\ImporterService\Importer\DataObjectImporter());
$instance->registerImporter('document', new \Pimcore\Translation\ImporterService\Importer\DocumentImporter());

return $instance;
