<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Helper\LongRunningHelper' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Helper'.\DIRECTORY_SEPARATOR.'LongRunningHelper.php';

$this->services['Pimcore\\Helper\\LongRunningHelper'] = $instance = new \Pimcore\Helper\LongRunningHelper(($this->services['doctrine'] ?? $this->getDoctrineService()));

$instance->setLogger(($this->services['monolog.logger.pimcore'] ?? $this->load('getMonolog_Logger_PimcoreService.php')));

return $instance;
