<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Workflow\Manager' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Manager.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Symfony'.\DIRECTORY_SEPARATOR.'Component'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Registry.php';

return $this->services['Pimcore\\Workflow\\Manager'] = new \Pimcore\Workflow\Manager(($this->privates['workflow.registry'] ?? ($this->privates['workflow.registry'] = new \Symfony\Component\Workflow\Registry())), ($this->privates['Pimcore\\Workflow\\EventSubscriber\\NotesSubscriber'] ?? $this->load('getNotesSubscriberService.php')), ($this->services['Pimcore\\Workflow\\ExpressionService'] ?? $this->load('getExpressionServiceService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
