<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Workflow\EventSubscriber\NotificationSubscriber' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'NotificationSubscriber.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Notification'.\DIRECTORY_SEPARATOR.'AbstractNotificationService.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Notification'.\DIRECTORY_SEPARATOR.'PimcoreNotificationService.php';

$a = ($this->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $this->getTranslatorInterfaceService());

return $this->privates['Pimcore\\Workflow\\EventSubscriber\\NotificationSubscriber'] = new \Pimcore\Workflow\EventSubscriber\NotificationSubscriber(($this->services['Pimcore\\Workflow\\Notification\\NotificationEmailService'] ?? $this->load('getNotificationEmailServiceService.php')), new \Pimcore\Workflow\Notification\PimcoreNotificationService(($this->services['Pimcore\\Model\\Notification\\Service\\NotificationService'] ?? $this->load('getNotificationServiceService.php')), $a), $a, ($this->services['Pimcore\\Workflow\\ExpressionService'] ?? $this->load('getExpressionServiceService.php')), ($this->services['Pimcore\\Workflow\\Manager'] ?? $this->load('getManagerService.php')));
