<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Image\Optimizer' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'ImageOptimizerInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'OptimizerInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'AbstractCommandOptimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'AdvancedPngOptimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'CjpegOptimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'JpegoptimOptimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'PngCrushOptimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'PngOutOptimizer.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'Optimizer'.\DIRECTORY_SEPARATOR.'ZopflipngOptimizer.php';

$this->services['Pimcore\\Image\\Optimizer'] = $instance = new \Pimcore\Image\Optimizer();

$instance->registerOptimizer(new \Pimcore\Image\Optimizer\AdvancedPngOptimizer());
$instance->registerOptimizer(new \Pimcore\Image\Optimizer\CjpegOptimizer());
$instance->registerOptimizer(new \Pimcore\Image\Optimizer\JpegoptimOptimizer());
$instance->registerOptimizer(new \Pimcore\Image\Optimizer\PngCrushOptimizer());
$instance->registerOptimizer(new \Pimcore\Image\Optimizer\PngOutOptimizer());
$instance->registerOptimizer(new \Pimcore\Image\Optimizer\ZopflipngOptimizer());

return $instance;
