<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.implementation_loader.object.layout' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'LoaderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'ClassNameLoaderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'ImplementationLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'DataObject'.\DIRECTORY_SEPARATOR.'ClassDefinition'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'LayoutLoaderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'DataObject'.\DIRECTORY_SEPARATOR.'ClassDefinition'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'LayoutLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'AbstractClassNameLoader.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Loader'.\DIRECTORY_SEPARATOR.'ImplementationLoader'.\DIRECTORY_SEPARATOR.'PrefixLoader.php';

return $this->services['pimcore.implementation_loader.object.layout'] = new \Pimcore\Model\DataObject\ClassDefinition\Loader\LayoutLoader([0 => new \Pimcore\Loader\ImplementationLoader\PrefixLoader([0 => '\\Pimcore\\Model\\DataObject\\ClassDefinition\\Layout\\', 1 => '\\Object_Class_Layout_'])]);
