<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pimcore.custom_report.adapter.factory.sql' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'models'.\DIRECTORY_SEPARATOR.'Tool'.\DIRECTORY_SEPARATOR.'CustomReport'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'CustomReportAdapterFactoryInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'models'.\DIRECTORY_SEPARATOR.'Tool'.\DIRECTORY_SEPARATOR.'CustomReport'.\DIRECTORY_SEPARATOR.'Adapter'.\DIRECTORY_SEPARATOR.'DefaultCustomReportAdapterFactory.php';

return $this->privates['pimcore.custom_report.adapter.factory.sql'] = new \Pimcore\Model\Tool\CustomReport\Adapter\DefaultCustomReportAdapterFactory('Pimcore\\Model\\Tool\\CustomReport\\Adapter\\Sql');
