<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pimcore.templating.view_helper.glossary' shared autowired service.

@trigger_error('The "pimcore.templating.view_helper.glossary" service is deprecated and will be removed in Pimcore 7', E_USER_DEPRECATED);

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Tool'.\DIRECTORY_SEPARATOR.'Glossary'.\DIRECTORY_SEPARATOR.'Processor.php';

return $this->services['pimcore.templating.view_helper.glossary'] = new \Pimcore\Templating\Helper\Glossary(new \Pimcore\Tool\Glossary\Processor(($this->services['Pimcore\\Http\\RequestHelper'] ?? $this->getRequestHelperService()), ($this->services['Pimcore\\Http\\Request\\Resolver\\EditmodeResolver'] ?? $this->getEditmodeResolverService()), ($this->services['Pimcore\\Http\\Request\\Resolver\\DocumentResolver'] ?? $this->getDocumentResolverService())));
