<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'presta_sitemap.dump_command' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Symfony'.\DIRECTORY_SEPARATOR.'Component'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'presta'.\DIRECTORY_SEPARATOR.'sitemap-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DumpSitemapsCommand.php';

$this->services['presta_sitemap.dump_command'] = $instance = new \Presta\SitemapBundle\Command\DumpSitemapsCommand(($this->services['router'] ?? $this->getRouterService()), ($this->services['presta_sitemap.dumper'] ?? $this->load('getPrestaSitemap_DumperService.php')), 'web');

$instance->setName('presta:sitemaps:dump');

return $instance;
