<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Targeting\DataProvider\Piwik' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Targeting'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'DataProviderInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Targeting'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'Piwik.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Analytics'.\DIRECTORY_SEPARATOR.'Piwik'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'VisitorClient.php';

$a = $this->load('getConfig2Service.php');

return $this->privates['Pimcore\\Targeting\\DataProvider\\Piwik'] = new \Pimcore\Targeting\DataProvider\Piwik($a, ($this->privates['Pimcore\\Analytics\\SiteId\\SiteIdProvider'] ?? $this->getSiteIdProviderService()), new \Pimcore\Analytics\Piwik\Api\VisitorClient(($this->privates['Pimcore\\Analytics\\Piwik\\Api\\ApiClient'] ?? $this->load('getApiClientService.php')), $a), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
