<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'presta_sitemap.generator' shared service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'presta'.\DIRECTORY_SEPARATOR.'sitemap-bundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UrlContainerInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'presta'.\DIRECTORY_SEPARATOR.'sitemap-bundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AbstractGenerator.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'presta'.\DIRECTORY_SEPARATOR.'sitemap-bundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GeneratorInterface.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'presta'.\DIRECTORY_SEPARATOR.'sitemap-bundle'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Generator.php';

$this->services['presta_sitemap.generator'] = $instance = new \Presta\SitemapBundle\Service\Generator(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['router'] ?? $this->getRouterService()), NULL, 3600, 50000);

$instance->setDefaults($this->parameters['presta_sitemap.defaults']);

return $instance;
