<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Piwik\ReportBroker' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Analytics'.\DIRECTORY_SEPARATOR.'Piwik'.\DIRECTORY_SEPARATOR.'ReportBroker.php';

return $this->privates['Pimcore\\Analytics\\Piwik\\ReportBroker'] = new \Pimcore\Analytics\Piwik\ReportBroker(($this->privates['Pimcore\\Analytics\\Piwik\\Config\\ConfigProvider'] ?? ($this->privates['Pimcore\\Analytics\\Piwik\\Config\\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider())), ($this->privates['Pimcore\\Analytics\\SiteId\\SiteIdProvider'] ?? $this->getSiteIdProviderService()), ($this->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $this->getTranslatorInterfaceService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
