<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Sitemap\EventListener\SitemapGeneratorListener' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Sitemap'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'SitemapGeneratorListener.php';
include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'ServiceCollection.php';

return $this->privates['Pimcore\\Sitemap\\EventListener\\SitemapGeneratorListener'] = new \Pimcore\Sitemap\EventListener\SitemapGeneratorListener(new \Pimcore\DependencyInjection\ServiceCollection(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pimcore_documents' => ['privates', 'Pimcore\\Sitemap\\Document\\DocumentTreeGenerator', 'getDocumentTreeGeneratorService.php', true],
], [
    'pimcore_documents' => '?',
]), [0 => 'pimcore_documents']));
