<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Workflow\Place\StatusInfo' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Place'.\DIRECTORY_SEPARATOR.'StatusInfo.php';

return $this->services['Pimcore\\Workflow\\Place\\StatusInfo'] = new \Pimcore\Workflow\Place\StatusInfo(($this->services['Pimcore\\Workflow\\Manager'] ?? $this->load('getManagerService.php')), ($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->services['Symfony\\Contracts\\Translation\\TranslatorInterface'] ?? $this->getTranslatorInterfaceService()));
