<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Google\Config\SiteConfigProvider' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Analytics'.\DIRECTORY_SEPARATOR.'Google'.\DIRECTORY_SEPARATOR.'Config'.\DIRECTORY_SEPARATOR.'SiteConfigProvider.php';

return $this->privates['Pimcore\\Analytics\\Google\\Config\\SiteConfigProvider'] = new \Pimcore\Analytics\Google\Config\SiteConfigProvider(($this->privates['Pimcore\\Analytics\\SiteId\\SiteIdProvider'] ?? $this->getSiteIdProviderService()), ($this->privates['Pimcore\\Analytics\\Google\\Config\\ConfigProvider'] ?? ($this->privates['Pimcore\\Analytics\\Google\\Config\\ConfigProvider'] = new \Pimcore\Analytics\Google\Config\ConfigProvider())));
