<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Pimcore\Http\Request\Resolver\TemplateResolver' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Request'.\DIRECTORY_SEPARATOR.'Resolver'.\DIRECTORY_SEPARATOR.'TemplateResolver.php';

return $this->services['Pimcore\\Http\\Request\\Resolver\\TemplateResolver'] = new \Pimcore\Http\Request\Resolver\TemplateResolver(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['pimcore.controller.config.config_normalizer'] ?? $this->getPimcore_Controller_Config_ConfigNormalizerService()));
