<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Analytics\Piwik\WidgetBroker' shared autowired service.

include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'pimcore'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Analytics'.\DIRECTORY_SEPARATOR.'Piwik'.\DIRECTORY_SEPARATOR.'WidgetBroker.php';

return $this->privates['Pimcore\\Analytics\\Piwik\\WidgetBroker'] = new \Pimcore\Analytics\Piwik\WidgetBroker(($this->privates['Pimcore\\Analytics\\Piwik\\Config\\ConfigProvider'] ?? ($this->privates['Pimcore\\Analytics\\Piwik\\Config\\ConfigProvider'] = new \Pimcore\Analytics\Piwik\Config\ConfigProvider())), ($this->privates['Pimcore\\Analytics\\Piwik\\Api\\ApiClient'] ?? $this->load('getApiClientService.php')), ($this->services['pimcore.cache.core.handler'] ?? $this->getPimcore_Cache_Core_HandlerService()), ($this->services['pimcore_admin.security.user_loader'] ?? $this->getPimcoreAdmin_Security_UserLoaderService()), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
