<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJaEbx1q\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJaEbx1q/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJaEbx1q.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJaEbx1q\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJaEbx1q\appAppKernelProdContainer([
    'container.build_hash' => 'JaEbx1q',
    'container.build_id' => '663331d6',
    'container.build_time' => 1617855187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJaEbx1q');
